In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv("Data/03_Library Systembook.csv")
df = df.dropna(how='all')
df['Customer ID'] = df['Customer ID'].astype('Int64')
df['Id'] = df['Id'].astype('Int64')
df['Book checkout'] = df['Book checkout'].astype(str).str.replace('32/05/2023','31/05/2023')
df['Book checkout'] = df['Book checkout'].astype(str).str.replace('"','')
df['Book checkout'] = pd.to_datetime(df['Book checkout'].str.replace('"','').str.strip(), format='%d/%m/%Y', errors='coerce')
df['Book Returned'] = pd.to_datetime(df['Book Returned'].str.replace('"','').str.strip(), format='%d/%m/%Y', errors='coerce')
df
df.to_csv("Data/03_Library Systembook_Cleaned.csv", index=False)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1
1,2,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2
2,3,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3
3,4,The hobbit,2023-04-02,2023-03-25,2 weeks,4
4,5,Dune,2023-04-02,2023-03-25,2 weeks,5
5,6,Little Women,2023-04-02,2023-05-01,2 weeks,1
6,7,IT,2063-04-10,2023-04-03,2 weeks,6
7,8,Misery,2023-04-15,2023-04-03,2 weeks,7
8,9,Catch 22,2023-04-15,2023-04-16,2 weeks,7
9,10,Animal Farm,2023-04-20,2023-04-24,2 weeks,2
10,11,1984,2023-04-23,2023-04-27,2 weeks,8
11,12,Little Women,2023-04-02,2023-05-01,2 weeks,1
12,13,East of Eden,2023-04-30,2023-05-05,2 weeks,2
13,14,America Is in the Heart,2023-05-01,2023-05-07,2 weeks,3
14,15,Wuthering Heights,2023-05-01,2023-05-10,2 weeks,9
15,16,Dark Tales,2023-05-15,2023-06-01,2 weeks,2
16,17,The Bloody Chamber,2023-05-31,2023-06-04,2 weeks,3
17,18,Les Miserables,2023-06-03,2023-06-07,2 weeks,5
18,19,Dracula,2023-06-10,2023-07-10,2 weeks,10
19,20,Frankenstein,2023-06-01,2023-06-20,2 weeks,2
20,21,NaN,2023-06-01,2023-06-05,2 weeks,<NA>

In [57]:
df2 = pd.read_csv("Data/03_Library SystemCustomers.csv")
df2 = df2.dropna(how='all')
df2['Customer ID'] = df2['Customer ID'].astype('Int64')
df2
df2.to_csv("Data/03_Library SystemCustomers_Cleaned.csv", index=False)

In [ ]:
def sayHello():
    print("Hello")

sayHello()

Hello

In [48]:
def sayHello2(name):
    print(f"Hello {name}")

sayHello2(name="Norma")

Hello Norma

In [58]:
df = pd.read_csv("Data/03_Library Systembook.csv")
df = df.dropna(how='all')
df['Customer ID'] = df['Customer ID'].astype('Int64')
df['Id'] = df['Id'].astype('Int64')
df['Book checkout'] = df['Book checkout'].astype(str).str.replace('32/05/2023','31/05/2023')
df['Book checkout'] = df['Book checkout'].astype(str).str.replace('"','')
df['Book checkout'] = pd.to_datetime(df['Book checkout'].str.replace('"','').str.strip(), format='%d/%m/%Y', errors='coerce')
df['Book Returned'] = pd.to_datetime(df['Book Returned'].str.replace('"','').str.strip(), format='%d/%m/%Y', errors='coerce')

def calculate_dates_difference(df, start_date, end_date, new_column):
    start_date = pd.to_datetime(df[start_date], errors='coerce')
    end_date = pd.to_datetime(df[end_date], errors='coerce')

    df[new_column] = (end_date - start_date).dt.days

    return df

df = calculate_dates_difference(
    df,
    start_date = "Book checkout",
    end_date = "Book Returned",
    new_column = "days_difference",
)

df.to_csv("Data/03_Library Systembook_Cleaned.csv", index=False)

df

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,days_difference
0,1,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1,5
1,2,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2,-3
2,3,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3,-4
3,4,The hobbit,2023-04-02,2023-03-25,2 weeks,4,-8
4,5,Dune,2023-04-02,2023-03-25,2 weeks,5,-8
5,6,Little Women,2023-04-02,2023-05-01,2 weeks,1,29
6,7,IT,2063-04-10,2023-04-03,2 weeks,6,-14617
7,8,Misery,2023-04-15,2023-04-03,2 weeks,7,-12
8,9,Catch 22,2023-04-15,2023-04-16,2 weeks,7,1
9,10,Animal Farm,2023-04-20,2023-04-24,2 weeks,2,4
10,11,1984,2023-04-23,2023-04-27,2 weeks,8,4
11,12,Little Women,2023-04-02,2023-05-01,2 weeks,1,29
12,13,East of Eden,2023-04-30,2023-05-05,2 weeks,2,5
13,14,America Is in the Heart,2023-05-01,2023-05-07,2 weeks,3,6
14,15,Wuthering Heights,2023-05-01,2023-05-10,2 weeks,9,9
15,16,Dark Tales,2023-05-15,2023-06-01,2 weeks,2,17
16,17,The Bloody Chamber,2023-05-31,2023-06-04,2 weeks,3,4
17,18,Les Miserables,2023-06-03,2023-06-07,2 weeks,5,4
18,19,Dracula,2023-06-10,2023-07-10,2 weeks,10,30
19,20,Frankenstein,2023-06-01,2023-06-20,2 weeks,2,19
20,21,NaN,2023-06-01,2023-06-05,2 weeks,<NA>,4

In [61]:
class Calculator:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def get_sum(self):
        return self.a + self.b
    
    def get_diff(self):
        return self.a - self.b
    
    def get_prod(self):
        return self.a * self.b
    
    def get_div(self):
        return self.a / self.b
    
if __name__ == "__main__":
    myCal = Calculator(a=3,b=2)
    print(myCal.get_sum())

5